apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-helm-alerts
  namespace: default
  labels:
    grafana_alert: "1"
data:
  backend-alerts.yaml: |
    apiVersion: 1

    groups:
      - orgId: 1
        name: application
        folder: Application Alerts
        interval: 10s

        rules:
          - uid: backend_target_down
            title: Backend Target Down
            condition: C

            data:
              - refId: A
                relativeTimeRange:
                  from: 60
                  to: 0
                datasourceUid: prometheus
                model:
                  datasource:
                    type: prometheus
                    uid: prometheus
                  editorMode: code
                  expr: 'min(up{job="backend"})'
                  instant: true
                  intervalMs: 1000
                  maxDataPoints: 43200
                  range: false
                  refId: A

              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold

            noDataState: Alerting
            execErrState: Alerting
            for: 10s

            annotations:
              summary: Backend target is down
              description: One or more backend targets are unavailable.

            labels:
              severity: warning
              service: backend

            isPaused: false
